adds version checks to cd

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -55,6 +55,8 @@ jobs:
           git commit -m "ci: bump version to $new_tag"
           git tag $new_tag
           git push origin main --follow-tags
+          # Ensure the push is complete by waiting a moment
+          sleep 10
 
   publish-npm:
     if: success()
@@ -68,9 +70,16 @@ jobs:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
+            ref: ${{ needs.bump-version.outputs.new_tag }}
             fetch-depth: 0
+
+        - name: Verify tag
+          run: |
+            if [ "$(git describe --tags)" != "${{ needs.bump-version.outputs.new_tag }}" ]; then
+              echo "Error: Expected tag ${{ needs.bump-version.outputs.new_tag }} but got $(git describe --tags)"
+              exit 1
+            fi
             
-        
         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
@@ -101,7 +110,15 @@ jobs:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
+            ref: ${{ needs.bump-version.outputs.new_tag }}
             fetch-depth: 0
+
+        - name: Verify tag
+          run: |
+            if [ "$(git describe --tags)" != "${{ needs.bump-version.outputs.new_tag }}" ]; then
+              echo "Error: Expected tag ${{ needs.bump-version.outputs.new_tag }} but got $(git describe --tags)"
+              exit 1
+            fi
         
         - name: Set up Node.js
           uses: actions/setup-node@v4
@@ -134,7 +151,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
+          ref: ${{ needs.bump-version.outputs.new_tag }}
           fetch-depth: 0
+
+      - name: Verify tag
+        run: |
+          if [ "$(git describe --tags)" != "${{ needs.bump-version.outputs.new_tag }}" ]; then
+            echo "Error: Expected tag ${{ needs.bump-version.outputs.new_tag }} but got $(git describe --tags)"
+            exit 1
+          fi
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -159,7 +184,15 @@ jobs:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
+            ref: ${{ needs.bump-version.outputs.new_tag }}
             fetch-depth: 0
+
+        - name: Verify tag
+          run: |
+            if [ "$(git describe --tags)" != "${{ needs.bump-version.outputs.new_tag }}" ]; then
+              echo "Error: Expected tag ${{ needs.bump-version.outputs.new_tag }} but got $(git describe --tags)"
+              exit 1
+            fi
     
         - name: Create release
           id: create_release
